services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-root}
    # Storage on disk every 60s, memory limit 256MB for cache, eviction policy - oldest with TTL
    command: "redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-root} --maxmemory 256mb --maxmemory-policy volatile-lru"
    networks:
      - cloud-network
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-root} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped
    ports:
      - '9091:9090'
      - '9001:9000'
    command: server ~/minio --console-address :9090
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    networks:
      - cloud-network
    volumes:
      - minio_data:/data



  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MULTIPLE_DATABASES: auth,users,public,attention,media,mind_track
      POSTGRES_USERNAME_AUTH: ${DB_USERNAME_AUTH}
      POSTGRES_PASSWORD_AUTH: ${DB_PASSWORD_AUTH}
      POSTGRES_USER_USER: ${DB_USERNAME_USER}
      POSTGRES_USER_PASSWORD: ${DB_PASSWORD_USER}
      POSTGRES_USERNAME_PUBLIC: ${DB_USERNAME_PUBLIC}
      POSTGRES_PASSWORD_PUBLIC: ${DB_PASSWORD_PUBLIC}
      POSTGRES_USERNAME_ATTENTION: ${DB_USERNAME_ATTENTION}
      POSTGRES_PASSWORD_ATTENTION: ${DB_PASSWORD_ATTENTION}
      POSTGRES_USERNAME_MEDIA: ${DB_USERNAME_MEDIA}
      POSTGRES_PASSWORD_MEDIA: ${DB_PASSWORD_MEDIA}
      POSTGRES_USERNAME_MIND_TRACK: ${DB_USERNAME_MIND_TRACK}
      POSTGRES_PASSWORD_MIND_TRACK: ${DB_PASSWORD_MIND_TRACK}
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - cloud-network
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # Cluster ID generation (required for KRaft)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  cloud-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  cache:
    driver: local