#!/bin/bash
set -e

# ÃÂ¡Ã‘â€šÃÂ²ÃÂ¾Ã‘â‚¬ÃÂµÃÂ½ÃÂ½Ã‘Â ÃÂ±ÃÂ°ÃÂ· ÃÂ´ÃÂ°ÃÂ½ÃÂ¸Ã‘â€¦
if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
    echo "ÃÂ¡Ã‘â€šÃÂ²ÃÂ¾Ã‘â‚¬Ã‘Å½Ã‘Å½ ÃÂ½ÃÂ°Ã‘ÂÃ‘â€šÃ‘Æ’ÃÂ¿ÃÂ½Ã‘â€“ ÃÂ±ÃÂ°ÃÂ·ÃÂ¸ ÃÂ´ÃÂ°ÃÂ½ÃÂ¸Ã‘â€¦: $POSTGRES_MULTIPLE_DATABASES"
    for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        echo "ÃÂ¡Ã‘â€šÃÂ²ÃÂ¾Ã‘â‚¬Ã‘Å½Ã‘Å½ ÃÂ±ÃÂ°ÃÂ·Ã‘Æ’ ÃÂ´ÃÂ°ÃÂ½ÃÂ¸Ã‘â€¦ $db"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE DATABASE $db;
EOSQL
    done
fi

# ÃÂ¡Ã‘â€šÃÂ²ÃÂ¾Ã‘â‚¬ÃÂµÃÂ½ÃÂ½Ã‘Â ÃÂºÃÂ¾Ã‘â‚¬ÃÂ¸Ã‘ÂÃ‘â€šÃ‘Æ’ÃÂ²ÃÂ°Ã‘â€¡Ã‘â€“ÃÂ² Ã‘â€“ ÃÂ½ÃÂ°ÃÂ´ÃÂ°ÃÂ½ÃÂ½Ã‘Â ÃÂ¿Ã‘â‚¬ÃÂ¸ÃÂ²Ã‘â€“ÃÂ»ÃÂµÃ‘â€”ÃÂ²
if [ -n "$POSTGRES_USERNAME_AUTH" ] && [ -n "$POSTGRES_PASSWORD_AUTH" ]; then
    echo "Create user to db auth"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $POSTGRES_USERNAME_AUTH WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_AUTH';
        ALTER USER $POSTGRES_USERNAME_AUTH WITH SUPERUSER;
        ALTER USER $POSTGRES_USERNAME_AUTH WITH CREATEDB;
        ALTER DATABASE auth OWNER TO $POSTGRES_USERNAME_AUTH;
        GRANT ALL PRIVILEGES ON DATABASE auth TO $POSTGRES_USERNAME_AUTH;
EOSQL
fi

if [ -n "$POSTGRES_USER_USER" ] && [ -n "$POSTGRES_USER_PASSWORD" ]; then
    echo "Create user to db users"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $POSTGRES_USER_USER WITH ENCRYPTED PASSWORD '$POSTGRES_USER_PASSWORD';
        ALTER USER $POSTGRES_USER_USER WITH SUPERUSER;
        ALTER USER $POSTGRES_USER_USER WITH CREATEDB;
        ALTER DATABASE users OWNER TO $POSTGRES_USER_USER;
        GRANT ALL PRIVILEGES ON DATABASE users TO $POSTGRES_USER_USER;

EOSQL
fi

if [ -n "$POSTGRES_USERNAME_PUBLIC" ] && [ -n "$POSTGRES_PASSWORD_PUBLIC" ]; then
    echo "Create user to db public"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $POSTGRES_USERNAME_PUBLIC WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_PUBLIC';
        ALTER USER $POSTGRES_USERNAME_PUBLIC WITH SUPERUSER;
        ALTER USER $POSTGRES_USERNAME_PUBLIC WITH CREATEDB;
        ALTER DATABASE public OWNER TO $POSTGRES_USERNAME_PUBLIC;
        GRANT ALL PRIVILEGES ON DATABASE public TO $POSTGRES_USERNAME_PUBLIC;
EOSQL
fi

if [ -n "$POSTGRES_USERNAME_ATTENTION" ] && [ -n "$POSTGRES_PASSWORD_ATTENTION" ]; then
    echo "Create user to db attention"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $POSTGRES_USERNAME_ATTENTION WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_ATTENTION';
        ALTER USER $POSTGRES_USERNAME_ATTENTION WITH SUPERUSER;
        ALTER USER $POSTGRES_USERNAME_ATTENTION WITH CREATEDB;
        ALTER DATABASE attention OWNER TO $POSTGRES_USERNAME_ATTENTION;
        GRANT ALL PRIVILEGES ON DATABASE attention TO $POSTGRES_USERNAME_ATTENTION;
EOSQL
fi

if [ -n "$POSTGRES_USERNAME_MEDIA" ] && [ -n "$POSTGRES_PASSWORD_MEDIA" ]; then
    echo "Create user to db media"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $POSTGRES_USERNAME_MEDIA WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_MEDIA';
        ALTER USER $POSTGRES_USERNAME_MEDIA WITH SUPERUSER;
        ALTER USER $POSTGRES_USERNAME_MEDIA WITH CREATEDB;
        ALTER DATABASE media OWNER TO $POSTGRES_USERNAME_MEDIA;
        GRANT ALL PRIVILEGES ON DATABASE media TO $POSTGRES_USERNAME_MEDIA;
EOSQL
fi

if [ -n "$POSTGRES_USERNAME_MIND_TRACK" ] && [ -n "$POSTGRES_PASSWORD_MIND_TRACK" ]; then
    echo "Create user to db mind_track"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $POSTGRES_USERNAME_MIND_TRACK WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_MIND_TRACK';
        ALTER USER $POSTGRES_USERNAME_MIND_TRACK WITH SUPERUSER;
        ALTER USER $POSTGRES_USERNAME_MIND_TRACK WITH CREATEDB;
        ALTER DATABASE mind_track OWNER TO $POSTGRES_USERNAME_MIND_TRACK;
        GRANT ALL PRIVILEGES ON DATABASE mind_track TO $POSTGRES_USERNAME_MIND_TRACK;
EOSQL
fi
